### ISSUE TITLE
Allow questions Post

### ISSUE THREAD

**Issue by neilshevlin** [hollymcevoy/Sweng-2022#9]
The Admin or the User should be able to ask some question from the chatbot and have it reference a specific document. 

The user should send a POST request. The post request will include such things as the ID of the document, the text of the question etc. The POST request must require certain parameters from the client in order to make a successful request. 

- [ ] Post question text
- [ ] body should contain the appropriate fields such as the doc ID and the text
- [ ] Should also do additional checks on the question, such as filtering for requests that are too long.

**Comment by yifanzhu1592** [comment]
For the document ID, should it be passed in the parameters or in the body?

**Comment by yifanzhu1592** [comment]
What should this function return?

**Comment by neilshevlin** [comment]
Added in commit 7af89af

Merged to dev
